CREATE TABLE movies
(
    id             INT PRIMARY KEY,
    cluster_number INT DEFAULT 0
);
CREATE TABLE viewers
(
    id INT PRIMARY KEY
);
CREATE TABLE ratings
(
    viewer_id INT NOT NULL,
    movie_id  INT NOT NULL,
    rating    NUMERIC,

    PRIMARY KEY (viewer_id, movie_id),
    FOREIGN KEY (movie_id) REFERENCES movies (id),
    FOREIGN KEY (viewer_id) REFERENCES viewers (id)
);


------------------------------------- SEQUENCE USAGE
-- @Id
-- @GeneratedValue(
--         strategy = GenerationType.SEQUENCE,
--         generator = "movie_id_generator"
-- )
-- @SequenceGenerator(
--         name = "movie_id_generator",
--         initialValue = 100,
--         sequenceName = "movie_seq",
--         allocationSize = 1,
--         schema = "bot"
--  )
-- @Column
-- private int id;
--
-- CREATE SEQUENCE movie_seq
--     START WITH 100
--     INCREMENT 1;
--
-- DROP SEQUENCE movie_seq;


-- INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100) PRIMARY KEY
------------------------------------- SEQUENCE USAGE